# Configuración de Resilience4j
resilience4j:
  # Configuración de Circuit Breaker
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6 # Tamaño de la ventana deslizante
        failure-rate-threshold: 50 # Umbral de tasa de fallos
        wait-duration-in-open-state: 20s # Duración de espera en estado abierto
        permitted-number-of-calls-in-half-open-state: 4 # Número de llamadas permitidas en estado medio abierto
        slow-call-duration-threshold: 3s # Umbral de duración de llamada lenta
        slow-call-rate-threshold: 50 # Umbral de tasa de llamadas lentas
    instances:
      products:
        baseConfig: default # Configuración base para el circuito de productos
  # Configuración de Time Limiter
  timelimiter:
    configs:
      default:
        timeout-duration: 4s # Duración del tiempo de espera
    instances:
      products:
        baseConfig: default # Configuración base para el limitador de tiempo de productos

# Configuración de Spring Cloud Gateway
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9100 # URI del emisor del JWT
      client:
        registration:
          client-app:
            provider: spring # Proveedor de OAuth2
            client-id: gateway-app # ID del cliente
            client-secret: 12345 # Secreto del cliente
            authorization-grant-type: authorization_code # Tipo de concesión de autorización
            redirect-uri: "http://127.0.0.1:8090/authorized" # URI de redirección
            scope:
              - openid # Alcance openid
              - profile # Alcance profile
            client-name: client-app # Nombre del cliente
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9100 # URI del emisor del JWT
  cloud:
    gateway:
      routes:
        - id: oauth-service
          uri: lb://oauth-service # lb=Balanceo de carga en oauth-service
          predicates:
                - Path=/api/security/** # Prefijo /api/oauth
          filters:
                - StripPrefix=2 # Elimina el segmento /api/oauth del prefijo
                - SetResponseHeader=Content-Type, application/json # Establece el encabezado de respuesta Content-Type
        - id: users-service
          uri: lb://users-service # lb=Balanceo de carga en users-service
          predicates:
              - Path=/api/users/** # Prefijo /api/users
          filters:
              - StripPrefix=2 # Elimina el segmento /api/users del prefijo
              - SetResponseHeader=Content-Type, application/json # Establece el encabezado de respuesta Content-Type
        - id: product-service
          uri: lb://product-service # lb=Balanceo de carga en product-service
          predicates:
            - Path=/api/products/** # Prefijo /api/product
            #- Header=token, 12345 #  Predicado de cabecera
            #- Method=GET, POST #  Predicado de método
            #- Query=color, verde #  Predicado de consulta
            #- Cookie=color, azul #  Predicado de cookie
          filters:
              - name: CircuitBreaker
                args:
                  name: products # Nombre del circuito
                  statusCodes: 500
                  fallbackUri: forward:/api/items/5 # Ruta de reenvío
              - StripPrefix=2 # Elimina el segmento /api/product del prefijo
              - name: SampleCookie
                args:
                  message: Hola este es mi mensaje personalizado para productos! # Mensaje personalizado para productos
                  name: user # Nombre del cookie
                  value: Exe # Valor del cookie
              - SetResponseHeader=Content-Type, application/json # Establece el encabezado de respuesta Content-Type
        - id: items-service
          uri: lb://items-service # Balanceo de carga en items-service
          predicates:
            - Path=/api/items/** # Prefijo /api/items
          filters:
            - StripPrefix=2 # Elimina el segmento /api/items del prefijo
            - AddRequestHeader=token-request, sdfasa # Añade un encabezado de solicitud
            - AddResponseHeader=token-response, asdfas # Añade un encabezado de respuesta
            - AddRequestParameter=name, Exe # Añade un parámetro de solicitud
            - SetResponseHeader=Content-Type, application/json # Establece el encabezado de respuesta Content-Type
